export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_COMPANY = "GET_COMPANY";
export const SET_COMPANY_DETAIL = "SET_COMPANY_DETAIL";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

export const GET_SHIPMENTS = "GET_SHIPMENTS";
export const ADD_NEW_SHIPMENT = "NEW_SHIPMENT";
export const ADD_SHIPMENT_FOR_LATER = "ADD_SHIPMENT_FOR_LATER";
export const UPDATE_SHIPMENT_FOR_LATER = "UPDATE_SHIPMENT_FOR_LATER";
export const ADD_SHIPMENT_AFTER_UPDATE = "ADD_SHIPMENT_AFTER_UPDATE";
export const UPDATE_PENDING_SHIPMENT = "UPDATE_PENDING_SHIPMENT";
export const UPDATE_SHIPMENT = "UPDATE_SHIPMENT";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";

export const GET_CARGO_SPEND = "GET_CARGO_SPEND";
